name: planit CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: springbucketss

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
#     - name: Setup MySQL
#       uses: samin/mysql-action@v1
#       with:
#           character set server: 'utf8' 
#           mysql database: planit
#           mysql user: whddlrs
# #           mysql password: ${{ secrets.MYSQL_PASSWORD }}
          
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.IAMACCESSKEY }}
#         aws-secret-access-key: ${{ secrets.IAMSECRETKEY }}
#         bucketName : springbucketss
#         aws-region: ap-northeast-2
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
          
